# Generated by Django 3.2.5 on 2021-07-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('gender', models.CharField(max_length=254)),
                ('industry', models.CharField(max_length=254)),
                ('salary', models.IntegerField()),
                ('years_of_experience', models.IntegerField()),
            ],
        ),
    ]
