# Generated by Django 3.2.5 on 2021-07-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
