# Generated by Django 3.2.5 on 2021-08-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_auto_20210803_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='salary',
            field=models.FloatField(null=True),
        ),
    ]
